[project]
name = "farmsim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kaggle>=2.2.4",
    "kaggle-environments>=1.32.6",
    "langchain>=1.3.14",
    "langchain-ollama>=1.1.0",
    "langgraph>=1.2.10",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.2",
]
